export type Item = {
  id: number;
  stockcode: string;
  longDesc: string;
  shortDesc: string;
  sansShadeDesc: string;
  stage: number | null;
  status: number | null;
  status_Factory: string;
  status_Market: string;
  pDFamilyName: string;
  familyName: string;
  category: number | null;
  style: number | null;
  function: number | null;
  skuType: number | null;
  sLType: number | null;
  supplier: string | null;
  baseCode: string;
  baseCodeDesc: string;
  baseCode_MKT: string;
  primaryFinishId: number | null;
  primaryFinishCd: string;
  primaryFinishDesc: string;
  secondaryFinishCd: string;
  secondaryFinishDesc: string;
  packaging: string;
  assembly: string;
  assemblyDetail: string;
  factoryItemNum: string;
  lampSKU: string;
  otherComponent: string;
  shadeSKU: string;
  shadeDesc: string;
  primaryMaterial: string;
  secondaryMaterial: string;
  shadeGlassTreatment: string;
  factShadeGlassCode: string;
  sLName: string;
  sLDesc: string;
  notes: string;
  height: string;
  width: string;
  extension: string;
  base: string;
  canopy: string;
  backplate: string;
  wiring: string;
  socketQty: string;
  socketType: string;
  socketDtl: string;
  socketDtl1: string;
  switch: string;
  wattage: string;
  wiringDtl: string;
  candleTube: string;
  harp: string;
  riser: string;
  finial: string;
  certification: string;
  createDate: Date | null;
  coordinator: number | null;
  select: number | null;
  size: string;
  drawingNum: string;
  shortDescPrv: string;
  hardwareFinishCd: string;
  hardwareFinish: string;
  hardwareMaterial: string;
  pdCode: string;
  highPoint: string;
  highPointNotes: string;
  rL601: string;
  rLPRCNotes: string;
  imagePath: string;
  priority: number | null;
  hPDisplay: string;
  primaryFinishCd_Fact: string;
  secondaryFinishCd_Fact: string;
  thirdFinishCd_Fact: string;
  sampleQty: number | null;
  reqDate: Date | null;
  stockcodePrv: string;
  basecodePrv: string;
  relatives: string;
  fixture_Height: string;
  height_as_shown: string;
  height_min: string;
  shade_details: string;
  mounting: string;
  bulbShape: string;
  certiType: string;
  certiNote: string;
  jBox: string;
  oAHeight: string;
  treatmentType: string;
  treatment: string;
  canopy_height: string;
  canopy_width: string;
  rod_Count: number | null;
  chain_Rod_Length: string;
  rod_Diameter: string;
  break_count: number | null;
  break_length: string;
  rod_Shape: string;
  title20: string;
  department: string;
  socket: string;
  sampleReqCompDt: Date | null;
  sampleConfCompDt: Date | null;
  sampleProjCompDt: Date | null;
  sampleActCompDt: Date | null;
  introdate: Date | null;
  pDStockcode: string;
  hTSMaterial: string;
  hTSMaterialDtl: string;
  priMtrlManufMethod: string;
  secMtrlManufMethod: string;
  thirdMtrlManufMethod: string;
  thirdMaterial: string;
  thirdFinishCd: string;
  thirdFinishDesc: string;
  sampleNotes: string;
  testing: string;
  shadeGlassReqd: string;
  pSSampleQtyReq: number | null;
  marketingDesignerDisplayText: string;
  marketingDesigner: number | null;
  royaltyDesignerDisplayText: string;
  royaltyDesigner: number | null;
  lightSource: string;
  lightQty: string;
  lEDType: string;
  lEDDriverType: string;
  lEDDimmingType: string;
  lEDLumens: string;
  lEDColorTemp: string;
  knobType: string;
  finialFinishCd: string;
  chainLink: string;
  chain: string;
  baseMaterial: string;
  baseFinishCd: string;
  baseFinishDesc: string;
  bC_DesignerSeq: number | null;
  bC_CategorySeq: number | null;
  subContVendor1: string;
  subContVendor1FactoryItem: string;
  subContVendor2: string;
  subContVendor2FactoryItem: string;
  subContVendor3: string;
  subContVendor3FactoryItem: string;
  subContVendor4: string;
  subContVendor4FactoryItem: string;
  subContVendor5: string;
  subContVendor5FactoryItem: string;
  exportToSandbox: number | null;
  groupName: string;
  romanticSize: string;
  fourACDesc: string;
  designGrouping: string;
  brandDisplayText: string;
  brand: number | null;
  solidworks3DFileAvail: number | null;
  internalReview: string;
  attachment: string;
  twp: string;
};

export type CreateItemRequest = {
  stockcode: string | null;
  shortDesc: string | null;
  stage: number | null;
  status: number | null;
  status_Factory: string;
  familyName: string | null;
  category: number | null;
  style: number | null;
  function: number | null;
  skuType: number | null;
  slType: number | null;
  supplier: number | null;
  baseCode: string | null;
  baseCode_MKT: string | null;
  primaryFinishId: number | null;
  createDate: Date | null;
  coordinator: number | null;
  drawingNum: string | null;
  pdCode: string | null;
  priority: number | null;
  introdate: Date | null;
  marketingDesigner: number | null;
  royaltyDesigner: number | null;
  brand: number | null;
  // attachment: string | null;
  // twp: string | null;
};
